# Site settings
title: "Laserdock and LaserOS Documentations"
description: "Converted from the original wiki format. Contains official documentation for Laserdock hardware, Laseros software, and related projects. Brought to you by the Laserdock Team from Wicked Lasers."
theme: jekyll-theme-slate

# Google Analytics (Optional)
google_analytics: [Your-UA-Code]

# Header button settings for built-in themes
show_downloads: true