# Site settings
title: "Laserdock and LaserOS Documentation"
description: "Official documentation for Laserdock hardware and LaserOS software. Brought to you by the Laserdock Team."

# Theme Selection
theme: jekyll-theme-slate

# CRITICAL FOR CUSTOM DOMAINS:
# Since you're using a subdomain, the baseurl must be empty
baseurl: "" 
url: "https://laserdockdocs.wickedlasers.com"

# Header settings
show_downloads: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-Xrue